### ISSUE TITLE
Support project identification in the URL

### ISSUE THREAD

**Issue by david-istvan** [geodes-sms/relis#39]
**Is your feature request related to a problem? Please describe.**
I wanted to provide a collaborator with a quick link to the Conflict's page of our project. The URL, however, does not allow this, because it is missing the project ID. If either of us has more than two projects, this, in principle, cannot be achieved by the current URL structure.

**Describe the solution you'd like**
Instead of this: http://relis.iro.umontreal.ca/op/entity_list/list_papers_screen_conflict.html, I would like this: http://relis.iro.umontreal.ca/[projectID]/screening/conflicts.html.
A REST-compatible URL would be nice.

**Comment by esyriani** [comment]
ReLiS uses session variables which stores the current project you are logged in. To access a specific page of another project, you need to first switch to the other project and then go to the link. ReLiS does not allow to easily jump between projects by design. Each project is a distinct entity with its own database to ensure privacy and data consistency.
